cabinet/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('index', index, name='index'),
    path('summary/<int:pk>', Summary.as_view(), name='summary'),
    path('receipt_list_cabinet', ReceiptList.as_view(), name='receipt_list_cabinet'),
    path('detail_receipt/<str:pk>', ReceiptDetail.as_view(), name='detail_receipt'),
    path('detail_flatservice/<int:pk>', FlatServiceDetail.as_view(), name='detail_flatservice'),
    path('receipt_pdf/<str:receipt_id>', render_pdf_view, name='receipt_pdf'),
    path('message_list/', MessageList.as_view(), name='message_list'),
    path('detail_message/<int:pk>', MessageDetail.as_view(), name='detail_message'),
    path('delete_messages', delete_message, name='delete_messages'),
    path('master_request_list', MasterRequestList.as_view(), name='master_request_list'),
    path('create_master_request', MasterRequestCreate.as_view(), name='create_master_request'),
    path('delete_master_request/<int:pk>', delete_master_request, name='delete_master_request'),
    path('owner_profile', OwnerProfile.as_view(), name='owner_profile'),
    path('update_owner/<int:pk>', UpdateOwner.as_view(), name='update_owner'),
    path('print_pdf/<int:receipt_id>', print_pdf, name='print_pdf')
]

main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', MainPageView.as_view(), name='main_page'),
    path('about_us', AboutUsPage.as_view(), name='about_us_page'),
    path('services', ServicePage.as_view(), name='service_page'),
    path('contacts', ContactPage.as_view(), name='contact_page')

]

myhouse/urls.py
from django.conf.urls import handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from myhouse import settings

urlpatterns = [
    path('admin_app/', include('admin_app.urls')),
    path('account/', include('account.urls')),
    path('cabinet/', include(('cabinet.urls', 'cabinet'), namespace='cabinet')),
    path('', include('main.urls')),
]
handler403 = 'admin_app.views.error_403'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cabinet/models.py
from django.db import models

# Create your models here.

account/forms.py
from django.contrib.auth.models import User
from django import forms

from account.models import *
from admin_app.models import *


class ProfileChangeForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['phone', 'role', 'status']
        widgets = {
            'phone': forms.TextInput(attrs={'data-mask': "(000)-000-00-00",
                                            'placeholder': '(000)-000-00-00'}),
        }


class UserChangeForm(forms.ModelForm):
    confirm_password = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput, required=False)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput, required=False)
    email = forms.EmailField(required=True, label='Адрес электроннной почты')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.id:
            self.fields['password'] = forms.CharField(label='Пароль', widget=forms.PasswordInput, required=True)
            self.fields['confirm_password'] = forms.CharField(label='Пароль', widget=forms.PasswordInput, required=True)

    def clean_password(self):
        password = self.cleaned_data['password']
        if password:
            return password
        else:
            return None

    def clean(self):
        try:
            if self.cleaned_data['password'] != '' and self.cleaned_data['confirm_password'] != '':
                password = self.cleaned_data['password']
                confirm_password = self.cleaned_data['confirm_password']
            else:
                raise forms.ValidationError('Введите пароли')
        except KeyError:
            raise forms.ValidationError('Введите пароли')
        if 'password' in self.changed_data:
            if password != confirm_password:
                raise forms.ValidationError(f'Пароли не совпадают')
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if 'email' in self.changed_data:
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError(f'Данный почтовый адрес уже зарегистрирован в системе')
        return email

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password', 'confirm_password']


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'E-mail'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Пользователь с email {email} не найден.')
        user = User.objects.filter(email=email).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        if not Profile.objects.filter(user_id=user.id).exists():
            raise forms.ValidationError('Пользователя не найдено')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['email', 'password']
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'E-mail или ID'
            })
        }


class LoginOwnerForm(LoginForm):

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Пользователь с email {email} не найден.')
        user = User.objects.filter(email=email).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        if not Owner.objects.filter(user_id=user.id).exists():
            raise forms.ValidationError('Пользователя не найдено')
        return self.cleaned_data


class OwnerFilterForm(forms.Form):
    id = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '1', 'id': 'owner_id'}))
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '2', 'id': 'fullname'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '3', 'id': 'phone'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '4', 'id': 'email'}))
    house = forms.ModelChoiceField(queryset=House.objects.all(), empty_label='',
                                   widget=forms.Select(attrs={'class': 'form-control', 'data-number': '5', 'id': 'house'}))
    flat = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '6', 'id': 'flat'}))
    date = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '7', 'id': 'date'}))
    status = forms.ChoiceField(choices=(('', ''), ('Активен', 'Активен'), ('Новый', 'Новый'), ('Отключен', 'Отключен')),
                               widget=forms.Select(attrs={'class': 'form-control', 'data-number': '8', 'id': 'status'}))
    debt = forms.ChoiceField(choices=(('', ''), ('Да', 'Да')),
                             widget=forms.Select(attrs={'class': 'form-control', 'data-number': '9', 'id': 'debt'}))


class OwnerChangeForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, error_messages={'invalid': "Только изображения"}, widget=forms.FileInput,
                              label="Сменить изображения")

    class Meta:
        model = Owner
        exclude = ['user', 'created']
        widgets = {
            'phone': forms.TextInput(attrs={'data-mask': "(000)-000-00-00",
                                            'placeholder': '(000)-000-00-00'}),
        }

cabinet/views.py
from django.contrib.auth import login, authenticate
from wkhtmltopdf.views import PDFTemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.edit import FormMixin, CreateView
from xhtml2pdf import pisa
from account.forms import *
from account.models import *
from admin_app.forms import ReceiptFilterForm, MasterRequestForm
from admin_app.models import Flat, Receipt, Message, logger, MasterRequest
from admin_app.views import FilterMixin
from myhouse import settings


# Create your views here.

class OwnerCabinet:

    def __init__(self, request):
        """
        Initialize the OwnerCabinet.
        """
        self.session = request.session
        users = self.session.get(settings.USERS_SESSION_ID)

        if not users:
            # save an empty cart in the session
            users = self.session[settings.USERS_SESSION_ID] = {}
        self.users = users

    def set_admin(self, admin):
        self.users['admin'] = admin
        self.save()

    def set_owner(self, owner):
        self.users['owner'] = owner
        self.save()

    def save(self):
        # mark the session as "modified" to make sure it gets saved
        self.session.modified = True

    def clear(self):
        # remove cart from session
        del self.session[settings.USERS_SESSION_ID]
        self.save()

    def login_owner(self, request):
        owner = User.objects.get(id=self.session[settings.USERS_SESSION_ID]['owner'])
        login(request, owner, backend='django.contrib.auth.backends.ModelBackend')

    def login_admin(self, request):
        admin = User.objects.get(id=self.session[settings.USERS_SESSION_ID]['admin'])
        login(request, admin, backend='django.contrib.auth.backends.ModelBackend')


def index(request):
    if request.GET.get('admin'):
        owner_cabinet = OwnerCabinet(request)
        owner_cabinet.set_admin(request.GET.get('admin'))
    return render(request, 'cabinet/index.html')


class Summary(DetailView):
    model = Flat
    template_name = 'cabinet/summary.html'

    def get_context_data(self, **kwargs):
        flat = Flat.objects.get(id=self.kwargs['pk'])
        context = {'flat': flat}
        return context


class ReceiptList(FormMixin, FilterMixin, ListView):
    model = Receipt
    form_class = ReceiptFilterForm
    template_name = 'cabinet/receipt/index.html'

    def get_context_data(self, **kwargs):
        flat = Flat.objects.get(owner_id=self.request.user.id)
        receipt_list = Receipt.objects.filter(flat_id=flat.id)

        return {'receipt_list': receipt_list, 'form': ReceiptFilterForm()}

    def get_form_kwargs(self, *args, **kwargs):
        # use GET parameters as the data
        kwargs = super().get_form_kwargs(*args, **kwargs)
        if self.request.method == 'GET':
            kwargs.update({
                'data': self.request.GET,
            })
        return kwargs


class ReceiptDetail(DetailView):
    model = Receipt
    template_name = 'cabinet/receipt/detail.html'


class FlatServiceDetail(DetailView):
    model = Flat
    template_name = 'cabinet/tariff/index.html'


class MessageList(ListView):
    model = Message
    template_name = 'cabinet/message/index.html'

    def get_context_data(self, **kwargs):
        context = {'message_list': Message.objects.filter(owner_id=self.request.user.id)}
        return context


class MessageDetail(DetailView):
    model = Message
    template_name = 'cabinet/message/detail.html'


def delete_message(request):
    logger.info(request.POST)
    Message.objects.filter(id__in=request.POST.getlist('ids[]')).delete()
    return redirect('/cabinet/message_list')


class MasterRequestList(ListView):
    model = MasterRequest
    template_name = 'cabinet/master_request/index.html'
    ordering = ['-id']

    def get_queryset(self):
        qs = super(MasterRequestList, self).get_queryset()
        user = User.objects.get(id=self.request.user.id)
        qs = qs.filter(flat__owner=user.owner)
        return qs


class MasterRequestCreate(CreateView):
    model = MasterRequest
    template_name = 'cabinet/master_request/create.html'
    form_class = MasterRequestForm
    success_url = reverse_lazy('cabinet:master_request_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        owner = Owner.objects.get(user_id=self.request.user.id)
        context['owner'] = owner.user_id
        return context

    
def delete_master_request(request, pk):
    MasterRequest.objects.get(id=pk).delete()
    return redirect('cabinet:master_request_list')


class OwnerProfile(LoginRequiredMixin, View):

    def get(self, request):
        owner = Owner.objects.get(user_id=request.user.id)
        return render(request, 'cabinet/owner/index.html', {'owner': owner})


class UpdateOwner(UpdateView):
    model = Owner
    template_name = 'cabinet/owner/update.html'

    def get_context_data(self, **kwargs):
        owner = Owner.objects.get(user_id=self.kwargs['pk'])
        print(owner)
        context = {
            'owner_form': OwnerChangeForm(instance=owner),
            'user_form': UserChangeForm(instance=owner.user)
        }
        return context

    def post(self, request, *args, **kwargs):
        owner = Owner.objects.get(user_id=self.kwargs['pk'])
        user_form = UserChangeForm(request.POST, instance=owner.user)
        owner_form = OwnerChangeForm(request.POST, request.FILES, instance=owner)
        if user_form.is_valid() and owner_form.is_valid():
            return self.form_valid(user_form, owner_form)
        else:
            return self.form_invalid(user_form, owner_form)

    def form_valid(self, user_form, owner_form):
        created_user = user_form.save()
        created_user.username = user_form.cleaned_data['email']
        if 'password' in user_form.changed_data:
            psw = user_form.cleaned_data['password']
            created_user.set_password(user_form.cleaned_data['password'])
        created_user.save()
        owner_form.save()
        email = user_form.cleaned_data['email']
        user = authenticate(self.request, username=email, password=user_form.cleaned_data['password'])
        login(self.request, user)
        return redirect('/cabinet/owner_profile')

    def form_invalid(self, user_form, owner_form):
        """If the form is invalid, render the invalid form."""
        context = {
            'owner_form': owner_form,
            'user_form': user_form
        }
        return self.render_to_response(context)


def render_pdf_view(request, receipt_id):
    template_path = 'cabinet/receipt/pdf.html'
    requisites = PaymentDetails.objects.first()
    receipt = Receipt.objects.get(id=receipt_id)
    # print(receipt.flat.owner.user.first_name)
    print(settings.STATIC_URL)
    context = {'requisites': requisites.description,
               'static': settings.STATIC_URL,
               'receipt': receipt}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
    # create a pdf
    pisa_status = pisa.CreatePDF(
       html.encode('UTF-8'), dest=response, encoding='utf-8')
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


def print_pdf(request, receipt_id):
    template_path = 'cabinet/receipt/pdf.html'
    requisites = PaymentDetails.objects.first()
    receipt = Receipt.objects.get(id=receipt_id)
    context = {'requisites': requisites.description,
               'static': settings.STATIC_URL,
               'receipt': receipt}
    template = get_template(template_path)
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="file.pdf"'
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse('Conversion failed!', status=404)

    return response

cabinet/templates/cabinet/receipt/detail.html
{% extends 'cabinet/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>Просмотр квитанции: #{{ receipt.id }}</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="/cabinet/index">Главная</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'cabinet:receipt_list_cabinet' %}">Квитанции</a></li>
                    <li class="breadcrumb-item active">Квитанция, №{{ receipt.id }}</li>
                </ol>
              </div>
            </div>
          </div>
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
            <div class="card-tools">
                <a href="{% url 'cabinet:print_pdf' receipt.id %}" target="_blank" class="btn btn-info btn-sm">
                    <i class="fa fa-print"></i>
                    <span>Распечатать</span>
                </a>
            </div>
        </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12">
                    <div class="table-responsive no-padding margin-top-15">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="width: 40px; min-width: 40px;">#</th>
                                    <th>Услуга</th>
                                    <th>Количество потребления (расход)</th>
                                    <th style="width: 80px; min-width: 80px;">Ед. изм.</th>
                                    <th>Цена за ед., грн</th>
                                    <th>Стоимость, грн</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <td colspan="5"></td>
                                    <td colspan="2"><b>Итого: {{ receipt.get_price }}</b></td>
                                </tr>
                            </tfoot>
                <tbody>
                {% for service in receipt.receiptservice_set.all %}
                    <tr role="row">
                            <td>{{ service.id }}</td>
                            <td>{{ service.service }}</td>
                            <td>{{ service.amount }}</td>
                            <td>{{ service.unit }}</td>
                            <td>{{ service.price_unit }}</td>
                            <td>{{ service.price }}</td>
                        </tr>
                {% endfor %}
                </tbody>
            </table>
                    </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="float-right">
                    <a href="{% url 'cabinet:receipt_pdf' receipt.id %}" class="btn btn-sm btn-warning" style="color: white;" download=""><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Скачать в PDF</a>
                    <a href="" class="btn btn-sm btn-success"><i class="fa fa-credit-card" aria-hidden="true"></i> Оплатить</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

cabinet/templates/cabinet/receipt/index.html
{% extends 'cabinet/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block header %}
      <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%}">
{% endblock %}
{% block content %}
        <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>Квитанции на оплату</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="/cabinet/index">Главная</a></li>
                  <li class="breadcrumb-item active">Квитанции</li>
                </ol>
              </div>
            </div>
          </div>
        </section>
    <section class="content">

        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-tools">
                            <a href="{% url 'cabinet:receipt_list_cabinet' %}" class="btn btn-default btn-sm">
                                <span class="hidden-sm">Очистить</span>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="table" class="table table-bordered table-hover sorting-table" data-filter-control="true" >
                            <thead>
                                <tr>
                                    <th>№ квитанции</th>
                                    <th>Дата</th>
                                    <th>Статус</th>
                                    <th>Сумма (грн.)</th>
                                </tr>
                            <tr id="w0-filters" class="filters">
                                <form method="get" id="filter-form">
                                    <td></td>
                                    <td>{{ form.date_range}}</td>
                                    <td>{{ form.status }}</td>
                                    <td></td>
                                </form>
                            </tr>
                            </thead>
                            <tbody>
                            {% for receipt in receipt_list %}
                                <tr class="clickable-row" href="{% url 'cabinet:detail_receipt' receipt.id %}">
                                    <td>{{ receipt.id }}</td>
                                <td>{{ receipt.date }}</td>
                                <td>{{ receipt.status }}</td>
                                    <td>{{ receipt.get_price }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
    <script src="{% static 'plugins/moment/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
    <script>
    $("#receipt").css('background-color', '#e1f1ea')




        let date = $('#id_date_range').daterangepicker({
            "autoUpdateInput": false,
            "showDropdowns": true,
            "opens": "center",
                locale: {
              format: 'YYYY-MM-DD'
            }
            }, function(start, end, label) {
            console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
            });
            $('#id_date_range').on('apply.daterangepicker', function(ev, picker) {
            $(this).val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.endDate.format('YYYY-MM-DD'));
            $(this).trigger('change');
        });



        $(document).ready(function () {
        $('#table').DataTable({
            dom: 'rtp',
            language: {
                paginate: {
                    "previous": "<<",
                    "next": ">>"
                }
            },

            columnDefs: [
                {orderable: false, targets: 0},
                {orderable: false, targets: 1},
                {orderable: false, targets: 2},
                {orderable: false, targets: 3},
            ],
            initComplete: function () {
                this.api()
                    .columns()
                    .every(function () {
                        let that = this;

                        $('#id_date_range, #id_status', this.header()).on('keyup change clear', function () {
                            if (that.search() !== this.value) {
                                that.search(this.value).draw();
                            }
                        });
                    });
            },
        });
    })

    </script>
{% endblock %}

cabinet/templates/cabinet/receipt/pdf.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        @font-face { font-family: Arial; src: url('cabinet/static/fonts/CaviarDreams.ttf'); }
        body{
          font-family: Arial;
            font-size: 16px;
        }

        td{
            padding-top: 4px;
            padding-left: 2px;
        }
        td{
            width: 100%
        }
        table {    -pdf-keep-in-frame-mode: shrink;}
    </style>
</head>
<body>

<table class="pdf-table">
    <tr>
        <td colspan="8" rowspan="4">Отримувач/Виконувач<br> {{ requisites }}</td>
        <td colspan="2">№ О/рахунку</td>

    </tr>
    <tr>
        <td colspan="2" style="font-size: 12px">{{ receipt.flat.bankbook_set.first }}</td>
    </tr>
    <tr>
        <td colspan="2">КВIТАНЦIЯ</td>
    </tr>
    <tr>
        <td colspan="2">{{receipt.id}}</td>
    </tr>
    <tr>
        <td colspan="2"> Платник </td>
        <td colspan="6">
            {{ receipt.flat.owner.user.last_name }} {{ receipt.flat.owner.user.first_name|slice:1 }}.
         {{ receipt.flat.owner.patronymic|slice:1 }}. {{ receipt.flat.house.address }} кв. {{ receipt.flat.number }}
        </td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td colspan="2"> Нараховано</td>
        <td>{{ receipt.get_price }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td colspan="2">Баланс о/р</td>
        <td>{{ receipt.flat.bankbook_set.first.balance }}</td>
        <td>на</td>
        <td colspan="2">{{ receipt.date}}</td>
        <td></td>
        <td></td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td colspan="2" rowspan="2">ДО СПЛАТИ</td>
        <td rowspan="2"> {{ receipt.get_price }}</td>
        <td rowspan="2">за</td>
        <td colspan="2" rowspan="2">{{ receipt.date }}</td>

    </tr>
    <tr>

    </tr>
    <tr>
        <td colspan="5" rowspan="2"></td>
        <td rowspan="2"></td>
    </tr>
    <tr>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
<table class="pdf-table">
    <thead>
    <tr>
        <th>Услуга</th>
        <th>Тариф</th>
        <th>Ед.Изм.</th>
        <th>Расход</th>
    </tr>
    </thead>
    <tbody>
    {% for service in receipt.receiptservice_set.all %}
        <tr>
            <td>{{ service.service }}</td>
            <td>{{ service.price_unit }}</td>
            <td>{{ service.service.unit }}</td>
            <td>{{ service.amount }}</td>
        </tr>
    {% endfor %}
    <tr>
        <td colspan="3" rowspan="2">РАЗОМ</td>
        <td rowspan="2">{{ receipt.get_price }}</td>
    </tr>
    <tr>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </tbody>

</table>
</body>
</html>