admin_app/urls.py
from django.urls import path
from django.views.defaults import permission_denied

from .services.build_from_template import BuildReceiptFileView
from .views import *
from .views_api import *

urlpatterns = [
    path('', IndexView.as_view(), name='statistic'),
    path('services/', CreateService.as_view(), name='services'),
    path('delete_service', delete_service, name='delete_service'),
    path('delete_unit', delete_unit, name='delete_unit'),
    path('tariff_list/', TariffList.as_view(), name='tariff_list'),
    path('create_tariff/', CreateTariff.as_view(), name='create_tariff'),
    path('update_tariff/<int:pk>', UpdateTariff.as_view(), name='update_tariff'),
    path('tariff/<int:pk>', ShowTariff.as_view(), name='tariff'),
    path('get_unit_by_service', get_unit_by_service, name='get_unit_by_service'),
    path('tariff_list/delete_tariff/<int:tariff_id>', delete_tariff, name='delete_tariff'),
    path('delete_service_tariff', delete_service_tariff, name='delete_service_tariff'),
    path('roles/', RoleList.as_view(), name='roles'),
    path('user_list/', UserList.as_view(), name='user_list'),
    path('create_user/', CreateUser.as_view(), name='create_user'),
    path('update_user/<int:pk>', UpdateUser.as_view(), name='update_user'),
    path('user_list/delete_user/<int:user_id>', delete_user, name='delete_user'),
    path('show_profile/<int:pk>', ShowProfile.as_view(), name='show_profile'),
    path('payment_details/', PaymentDetailsView.as_view(), name='payment_details'),
    path('payment_items/', PaymentItemList.as_view(), name='payment_items'),
    path('create_payment/', PaymentItemCreate.as_view(), name='create_payment'),
    path('update_payment/<int:pk>', PaymentItemUpdate.as_view(), name='update_payment'),
    path('payment_items/delete_payment/<int:payment_id>', delete_payment, name='delete_payment'),
    path('main_page/', MainPageView.as_view(), name='main_pagev'),
    path('info_page/', InfoPage.as_view(), name='info_pagev'),
    path('service_page/', ServicePageView.as_view(), name='service_pagev'),
    path('contact_page/', ContactPageView.as_view(), name='contact_pagev'),
    path('delete_document/<int:pk>', delete_document, name='delete_document'),
    path('delete_image_gallery/<int:image_id>', delete_from_gallery, name='delete_image'),
    path('delete_service_page/<int:service_id>', delete_service_page, name='delete_service_page'),
    path('clone_tariff/<int:pk>', CloneTariff.as_view(), name='clone_tariff'),
    path('owner_list/', OwnerList.as_view(), name='owner_list'),
    path('create_owner', CreateOwner.as_view(), name='create_owner'),
    path('update_owner/<int:pk>', UpdateOwner.as_view(), name='update_owner'),
    path('detail_owner/<int:pk>', DetailOwner.as_view(), name='detail_owner'),
    path('delete_owner/<int:owner_id>', delete_owner, name='delete_owner'),
    path('invite/', InviteView.as_view(), name='invite'),

    path('house_list', HouseList.as_view(), name='house_list'),
    path('create_house', CreateHouse.as_view(), name='create_house'),
    path('update_house/<int:pk>', UpdateHouse.as_view(), name='update_house'),
    path('detail_house/<int:pk>', HouseDetail.as_view(), name='detail_house'),
    path('delete_house/<int:house_id>', delete_house, name='delete_house'),

    path('flat_list', FlatList.as_view(), name='flat_list'),
    path('get_section_level', get_section_level, name='get_section_level'),
    path('create_flat', CreateFlat.as_view(), name='create_flat'),
    path('update_flat/<int:pk>', UpdateFlat.as_view(), name='update_flat'),
    path('detail_flat/<int:pk>', FlatDetail.as_view(), name='detail_flat'),
    path('delete_flat/<int:pk>', delete_flat, name='delete_flat'),

    path('counter_list', CounterView.as_view(), name='counter_list'),
    path('create_counter', CreateCounter.as_view(), name='create_counter'),
    path('flat_counter_list/<int:pk>', FlatCounterList.as_view(), name='flat_counter_list'),
    path('detail_counter/<str:pk>', CounterDetail.as_view(), name='counter_detail'),
    path('update_counter/<str:pk>', UpdateCounter.as_view(), name='update_counter'),
    path('delete_counter/<str:counter_id>', delete_counter, name='delete_counter'),
    path('get_section_flat', get_section_flat, name='get_section_flat'),
    path('get_flats', get_flats, name='get_flats'),
    path('get_flats_by_owner', get_flats_by_owner, name='get_flats_by_owner'),

    path('cashbox_list', CashBoxList.as_view(), name='cashbox_list'),
    path('create_income', CreateIncome.as_view(), name='create_income'),
    path('update_income/<int:pk>', UpdateIncome.as_view(), name='update_income'),
    path('create_expense', CreateExpense.as_view(), name='create_expense'),
    path('update_expense/<int:pk>', UpdateExpense.as_view(), name='update_expense'),
    path('export_cashbox', export_cashbox, name='export_cashbox'),
    path('detail_cashbox/<str:pk>', CashBoxDetail.as_view(), name='detail_cashbox'),
    path('delete_cashbox/<str:cash_box_id>', delete_cash_box, name='delete_cashbox'),

    path('bankbook_list', BankBookList.as_view(), name='bankbook_list'),
    path('get_bankbooks', get_bankbooks, name='get_bankbooks'),
    path('create_bankbook', CreateBankBook.as_view(), name='create_bankbook'),
    path('update_bankbook/<str:pk>', UpdateBankBook.as_view(), name='update_bankbook'),
    path('detail_bankbook/<str:pk>', BankbookDetail.as_view(), name='detail_bankbook'),
    path('delete_bankbook/<str:bankbook_id>', delete_bankbook, name='delete_bankbook'),
    path('export_bankbook', export_bankbook, name='export_bankbook'),
    path('get_service', get_service, name='get_service'),
    path('get_owner', get_owner, name='get_owner'),

    path('receipt_list', ReceiptList.as_view(), name='receipt_list'),
    path('delete_receipts', delete_receipt, name='delete_receipts'),
    path('delete_receipt/<str:receipt_id>', delete_receipt, name='delete_receipt'),
    path('create_receipt', CreateReceipt.as_view(), name='create_receipt'),
    path('update_receipt/<str:pk>', UpdateReceipt.as_view(), name='update_receipt'),
    path('detail_receipt/<str:pk>', ReceiptDetail.as_view(), name='detail_receipt'),
    path('get_counters', get_counters, name='get_counters'),

    path('master_request_list', MasterRequestList.as_view(), name='master_request_list'),
    path('create_master_request', MasterRequestCreate.as_view(), name='create_master_request'),
    path('update_master_request/<int:pk>', MasterRequestUpdate.as_view(), name='update_master_request'),
    path('detail_master_request/<int:pk>', MasterRequestDetail.as_view(), name='detail_master_request'),
    path('delete_master_request/<str:pk>', delete_master_request, name='delete_master_request'),

    path('message_list', MessageList.as_view(), name='message_list'),
    path('create_message', MessageCreate.as_view(), name='create_message'),
    path('detail_message/<int:pk>', MessageDetail.as_view(), name='detail_message'),
    path('delete_messages', delete_message, name='delete_messages'),

    path('export_transaction/<int:pk>', export_transaction, name='export_transaction'),

    path('house_search/<int:page>', house_search, name='house_search'),
    path('owner_search/<int:page>', owner_search, name='owner_search'),
    path('bankbook_search/<int:page>', bankbook_search, name='bankbook_search'),

    path('receipt/template_choose/', TemplateChooseView.as_view(), name='template_choose'),
    path('receipt/template_create/', ReceiptTemplateCreateView.as_view(), name='template_create'),
    path('receipt/build_receipt_file/', BuildReceiptFileView.as_view(), name='build_receipt_file'),
    path('receipt/send/', ReceiptToEmailSend.as_view(), name='send_receipt'),
    path('receipt/template/<int:template_pk>/', TemplateDefault.as_view(), name='template_default'),
    path('receipt/delete_template/<int:template_id>/', delete_template, name='delete_template'),

]

main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', MainPageView.as_view(), name='main_page'),
    path('about_us', AboutUsPage.as_view(), name='about_us_page'),
    path('services', ServicePage.as_view(), name='service_page'),
    path('contacts', ContactPage.as_view(), name='contact_page')

]

myhouse/urls.py
from django.conf.urls import handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from myhouse import settings

urlpatterns = [
    path('admin_app/', include('admin_app.urls')),
    path('account/', include('account.urls')),
    path('cabinet/', include(('cabinet.urls', 'cabinet'), namespace='cabinet')),
    path('', include('main.urls')),
]
handler403 = 'admin_app.views.error_403'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/forms.py
from django.contrib.auth.models import User
from django import forms

from account.models import *
from admin_app.models import *


class ProfileChangeForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['phone', 'role', 'status']
        widgets = {
            'phone': forms.TextInput(attrs={'data-mask': "(000)-000-00-00",
                                            'placeholder': '(000)-000-00-00'}),
        }


class UserChangeForm(forms.ModelForm):
    confirm_password = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput, required=False)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput, required=False)
    email = forms.EmailField(required=True, label='Адрес электроннной почты')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.id:
            self.fields['password'] = forms.CharField(label='Пароль', widget=forms.PasswordInput, required=True)
            self.fields['confirm_password'] = forms.CharField(label='Пароль', widget=forms.PasswordInput, required=True)

    def clean_password(self):
        password = self.cleaned_data['password']
        if password:
            return password
        else:
            return None

    def clean(self):
        try:
            if self.cleaned_data['password'] != '' and self.cleaned_data['confirm_password'] != '':
                password = self.cleaned_data['password']
                confirm_password = self.cleaned_data['confirm_password']
            else:
                raise forms.ValidationError('Введите пароли')
        except KeyError:
            raise forms.ValidationError('Введите пароли')
        if 'password' in self.changed_data:
            if password != confirm_password:
                raise forms.ValidationError(f'Пароли не совпадают')
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if 'email' in self.changed_data:
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError(f'Данный почтовый адрес уже зарегистрирован в системе')
        return email

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password', 'confirm_password']


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'E-mail'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Пользователь с email {email} не найден.')
        user = User.objects.filter(email=email).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        if not Profile.objects.filter(user_id=user.id).exists():
            raise forms.ValidationError('Пользователя не найдено')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['email', 'password']
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'E-mail или ID'
            })
        }


class LoginOwnerForm(LoginForm):

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Пользователь с email {email} не найден.')
        user = User.objects.filter(email=email).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        if not Owner.objects.filter(user_id=user.id).exists():
            raise forms.ValidationError('Пользователя не найдено')
        return self.cleaned_data


class OwnerFilterForm(forms.Form):
    id = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '1', 'id': 'owner_id'}))
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '2', 'id': 'fullname'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '3', 'id': 'phone'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '4', 'id': 'email'}))
    house = forms.ModelChoiceField(queryset=House.objects.all(), empty_label='',
                                   widget=forms.Select(attrs={'class': 'form-control', 'data-number': '5', 'id': 'house'}))
    flat = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '6', 'id': 'flat'}))
    date = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'data-number': '7', 'id': 'date'}))
    status = forms.ChoiceField(choices=(('', ''), ('Активен', 'Активен'), ('Новый', 'Новый'), ('Отключен', 'Отключен')),
                               widget=forms.Select(attrs={'class': 'form-control', 'data-number': '8', 'id': 'status'}))
    debt = forms.ChoiceField(choices=(('', ''), ('Да', 'Да')),
                             widget=forms.Select(attrs={'class': 'form-control', 'data-number': '9', 'id': 'debt'}))


class OwnerChangeForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, error_messages={'invalid': "Только изображения"}, widget=forms.FileInput,
                              label="Сменить изображения")

    class Meta:
        model = Owner
        exclude = ['user', 'created']
        widgets = {
            'phone': forms.TextInput(attrs={'data-mask': "(000)-000-00-00",
                                            'placeholder': '(000)-000-00-00'}),
        }

admin_app/templates/admin_app/master_request/create.html
{% extends 'admin_app/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block header %}
      <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%}">
    <link rel="stylesheet" href="{% static 'dist/css/timepicker.min.css' %}">
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>Новая заявка</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="/admin_app">Главная</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'master_request_list' %}">Заявки</a></li>
                    <li class="breadcrumb-item active">Новая заявка</li>
                </ol>
              </div>
            </div>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xs-12 col-md-7 col-lg-6">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="input-group date">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fa fa-calendar-alt"></i></div>
                                    </div>
                                    {{ form.date|add_class:"form-control" }}
                                </div>
                                <div class="label-mid ml-1 mr-1">от</div>
                                <div class="input-group time">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="far fa-clock"></i></div>
                                    </div>
                                    {{ form.time|add_class:"form-control" }}
                                </div>
                            </div>
                        </div>
                    </div>
          </div>
    </section>
    <section class="content">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <div class="col-xs-12 col-md-8">
                            <label class=" requiredField">
                                Владелец квартиры
                            </label>
                            <div class="input-group">
                                {{ form.owner|add_class:"form-control" }}
                            </div>
                        </div>

                    </div>
                    <div class="col-xs-12 col-md-6"></div>
                    <div class="col-xs-12 col-md-6">
                        <div class="col-xs-12 col-md-8">
                            <label class=" requiredField">
                                Описание
                            </label>
                            <div class="input-group">
                               {{ form.description|add_class:"form-control" }}
                            </div>

                        </div>

                    </div>
                    <div class="col-xs-12 col-md-6">
                        <div class="col-xs-12 col-md-8">
                            <label class=" requiredField">
                                Квартира
                            </label>
                            <div class="input-group">
                                {{ form.flat|add_class:"form-control" }}
                            </div>

                        </div>
                        <div class="col-xs-12 col-md-8">
                            <label class=" requiredField">
                                Тип
                            </label>
                            <div class="input-group">
                                {{ form.type|add_class:"form-control" }}
                            </div>

                        </div>
                        <div class="col-xs-12 col-md-8">
                            <label class=" requiredField">
                                Статаус
                            </label>
                            <div class="input-group">
                                {{ form.status|add_class:"form-control" }}
                            </div>

                        </div>
                        <div class="col-xs-12 col-md-8">
                            <label class=" requiredField">
                                Мастер
                            </label>
                            <div class="input-group">
                                {{ form.master|add_class:"form-control" }}
                            </div>

                        </div>




                    </div>
                    <div class="col-xs-12 col-md-12">
                        <div class="col-xs-12 col-md-8">
                            <label class=" requiredField">
                                Коментарий
                            </label>
                            <div class="input-group">
                                {{ form.comment|add_class:"form-control" }}
                            </div>

                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group float-right">
                            <a href="{% url 'master_request_list' %}" class="btn btn-default">Отменить</a>
                            <button type="submit" class="btn btn-success" name="save-action">Сохранить</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </form>
{% endblock %}
{% block script %}
    <script src="{% static 'plugins/moment/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'dist/js/timepicker.min.js'%}"></script>
    <script src="{% static 'dist/js/section_flat.js' %}"></script>

    <script>

    $('.nav-link.active').removeClass('active');
        $('.nav-link').find('p:contains("Заявки вызова мастера")').parents('.nav-link').addClass('active');

    let date = $('#id_date').daterangepicker({
    "singleDatePicker": true,
    "showDropdowns": true,
        "startDate": parseInt(moment().format('DD.MM.YYYY'),10),
    "opens": "center",
        locale: {
      format: 'DD.MM.YYYY'
    }
}, function(start, end, label) {
  console.log('New date range selected: ' + start.format('DD.MM.YYYY') + ' to ' + end.format('DD.MM.YYYY') + ' (predefined range: ' + label + ')');
});
    $('#id_time').val(moment().format('HH:mm'),10);
    $('#id_time').timepicker();

    $('#id_owner').on('change', function (){
        get_flats_by_owner($(this).val());
    });

    </script>
{% endblock %}

admin_app/templates/admin_app/master_request/index.html
{% extends 'admin_app/base.html' %}
{% load static %}
{% block header %}
      <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%}">
{% endblock %}
{% block content %}
        <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>Заявки вызова мастера</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="/admin_app">Главная</a></li>
                  <li class="breadcrumb-item active">Заявки вызова мастера</li>
                </ol>
              </div>
            </div>
          </div>
    </section>

     <section class="content">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="float-right mb-2 mt-2">
                    <a href="{% url 'create_master_request' %}" class="btn btn-success">Добавить заявку</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="card">
                <div class="card-header">
                    <div class="card-tools">
                    <a href="{% url 'master_request_list' %}" class="btn btn-default btn-sm">
                        <span class="hidden-sm">Очистить</span>
                    </a>
                </div>
                </div>
                    <div class="card-body">
                    <form method="get" id="filter-form">
                        <table id="application-table" class="table table-bordered table-hover sorting-table" data-filter-control="true" >
                            <thead>
                                <tr>
                                    <th>№ заявки</th>
                                    <th>Удобное время</th>
                                    <th>Тип мастера</th>
                                    <th>Описание</th>
                                    <th>Квартира</th>
                                    <th>Владелец</th>
                                    <th>Телефон</th>
                                    <th>Мастер</th>
                                    <th>Статус</th>
                                    <th style="width: 114px; min-width: 114px">&nbsp;</th>
                                </tr>
                            <tr id="w0-filters" class="filters">

                                <td>{{ form.id }}</td>
                                <td>{{ form.date_range }}</td>
                                <td>{{ form.type }}</td>
                                <td>{{ form.description }}</td>
                                <td>{{ form.flat__number }}</td>
                                <td>{{ form.flat__owner_id }}</td>
                                <td>{{ form.flat__owner_phone }}</td>
                                <td>{{ form.master_id }}</td>
                                <td>{{ form.status }}</td>
                                <td></td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for masterrequest in masterrequest_list %}
                                <tr class="clickable-row" href="{% url 'detail_master_request' masterrequest.id %}">
                                    <td>{{ masterrequest.id }}</td>
                                    <td>{{ masterrequest.date }} - {{ masterrequest.time }}</td>
                                    <td>{{ masterrequest.type }}</td>
                                    <td>{{ masterrequest.description }}</td>
                                    <td>{{ masterrequest.flat }}</td>
                                    <td>{{ masterrequest.flat.owner }}</td>
                                    <td>{{ masterrequest.flat.owner.phone }}</td>
                                    <td>{{ masterrequest.master }}</td>
                                    <td>
                                        {% if masterrequest.status == 'новое' %}
                                            <small class="badge badge-primary">{{ masterrequest.status }}</small>
                                        {% elif masterrequest.status == 'в процессе' %}
                                            <small class="badge badge-warning">{{ masterrequest.status }}</small>
                                        {% else %}
                                            <small class="badge badge-success">{{ masterrequest.status }}</small>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <div class="btn-group float-right">
                                            <a class="btn btn-default btn-sm" href="{% url 'update_master_request' masterrequest.id %}" title="Редактировать" data-toggle="tooltip"><i class="fas fa-pencil-alt"></i></a>
                                            <a class="btn btn-default btn-sm" href="{% url 'delete_master_request' masterrequest.id %}" title="Удалить"><i class="fa fa-trash"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </form>
                    </div>
                </div>
            </div>
        </div>
     </section>
{% endblock %}
{% block script %}
       <script src="{% static 'plugins/moment/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
    <script>

    $('.nav-link.active').removeClass('active');
        $('.nav-link').find('p:contains("Заявки вызова мастера")').parents('.nav-link').addClass('active');



        let date = $('#id_date_range').daterangepicker({
            "autoUpdateInput": false,
    "showDropdowns": true,
    "opens": "center",
        locale: {
      format: 'YYYY-MM-DD'
    }
}, function(start, end, label) {
  console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
});
        $('#id_date_range').on('apply.daterangepicker', function(ev, picker) {
      $(this).val(picker.startDate.format('YYYY-MM-DD') + ' - ' + picker.endDate.format('YYYY-MM-DD'));
      $(this).trigger('change');
  });

        $('#id_date_range').on('cancel.daterangepicker', function(ev, picker) {
  //do something, like clearing an input
  $('#id_date_range').val('');
  $(this).trigger('change');
});



        $(document).ready(function () {
        $('#application-table').DataTable({
            ordering: false,
            dom: 'rtp',
            language: {
                paginate: {
                    "previous": "<<",
                    "next": ">>"
                }
            },

            initComplete: function () {
                this.api()
                    .columns()
                    .every(function () {
                        let that = this;

                        $('#id_id, #id_date_range, #id_type, #id_description, #id_flat__number, #id_flat__owner_id, #id_flat__owner_phone, #id_master_id, #id_status', this.header()).on('keyup change clear', function () {
                            console.log(this.id)
                            if (that.search() !== this.value) {
                                that.search(this.value).draw();
                            }
                        });
                    });
            },
        });
    })

    </script>
{% endblock %}