cabinet/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('index', index, name='index'),
    path('summary/<int:pk>', Summary.as_view(), name='summary'),
    path('receipt_list_cabinet', ReceiptList.as_view(), name='receipt_list_cabinet'),
    path('detail_receipt/<str:pk>', ReceiptDetail.as_view(), name='detail_receipt'),
    path('detail_flatservice/<int:pk>', FlatServiceDetail.as_view(), name='detail_flatservice'),
    path('receipt_pdf/<str:receipt_id>', render_pdf_view, name='receipt_pdf'),
    path('message_list/', MessageList.as_view(), name='message_list'),
    path('detail_message/<int:pk>', MessageDetail.as_view(), name='detail_message'),
    path('delete_messages', delete_message, name='delete_messages'),
    path('master_request_list', MasterRequestList.as_view(), name='master_request_list'),
    path('create_master_request', MasterRequestCreate.as_view(), name='create_master_request'),
    path('delete_master_request/<int:pk>', delete_master_request, name='delete_master_request'),
    path('owner_profile', OwnerProfile.as_view(), name='owner_profile'),
    path('update_owner/<int:pk>', UpdateOwner.as_view(), name='update_owner'),
    path('print_pdf/<int:receipt_id>', print_pdf, name='print_pdf')
]

main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', MainPageView.as_view(), name='main_page'),
    path('about_us', AboutUsPage.as_view(), name='about_us_page'),
    path('services', ServicePage.as_view(), name='service_page'),
    path('contacts', ContactPage.as_view(), name='contact_page')

]

myhouse/urls.py
from django.conf.urls import handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from myhouse import settings

urlpatterns = [
    path('admin_app/', include('admin_app.urls')),
    path('account/', include('account.urls')),
    path('cabinet/', include(('cabinet.urls', 'cabinet'), namespace='cabinet')),
    path('', include('main.urls')),
]
handler403 = 'admin_app.views.error_403'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cabinet/models.py
from django.db import models

# Create your models here.

cabinet/views.py
from django.contrib.auth import login, authenticate
from wkhtmltopdf.views import PDFTemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.edit import FormMixin, CreateView
from xhtml2pdf import pisa
from account.forms import *
from account.models import *
from admin_app.forms import ReceiptFilterForm, MasterRequestForm
from admin_app.models import Flat, Receipt, Message, logger, MasterRequest
from admin_app.views import FilterMixin
from myhouse import settings


# Create your views here.

class OwnerCabinet:

    def __init__(self, request):
        """
        Initialize the OwnerCabinet.
        """
        self.session = request.session
        users = self.session.get(settings.USERS_SESSION_ID)

        if not users:
            # save an empty cart in the session
            users = self.session[settings.USERS_SESSION_ID] = {}
        self.users = users

    def set_admin(self, admin):
        self.users['admin'] = admin
        self.save()

    def set_owner(self, owner):
        self.users['owner'] = owner
        self.save()

    def save(self):
        # mark the session as "modified" to make sure it gets saved
        self.session.modified = True

    def clear(self):
        # remove cart from session
        del self.session[settings.USERS_SESSION_ID]
        self.save()

    def login_owner(self, request):
        owner = User.objects.get(id=self.session[settings.USERS_SESSION_ID]['owner'])
        login(request, owner, backend='django.contrib.auth.backends.ModelBackend')

    def login_admin(self, request):
        admin = User.objects.get(id=self.session[settings.USERS_SESSION_ID]['admin'])
        login(request, admin, backend='django.contrib.auth.backends.ModelBackend')


def index(request):
    if request.GET.get('admin'):
        owner_cabinet = OwnerCabinet(request)
        owner_cabinet.set_admin(request.GET.get('admin'))
    return render(request, 'cabinet/index.html')


class Summary(DetailView):
    model = Flat
    template_name = 'cabinet/summary.html'

    def get_context_data(self, **kwargs):
        flat = Flat.objects.get(id=self.kwargs['pk'])
        context = {'flat': flat}
        return context


class ReceiptList(FormMixin, FilterMixin, ListView):
    model = Receipt
    form_class = ReceiptFilterForm
    template_name = 'cabinet/receipt/index.html'

    def get_context_data(self, **kwargs):
        flat = Flat.objects.get(owner_id=self.request.user.id)
        receipt_list = Receipt.objects.filter(flat_id=flat.id)

        return {'receipt_list': receipt_list, 'form': ReceiptFilterForm()}

    def get_form_kwargs(self, *args, **kwargs):
        # use GET parameters as the data
        kwargs = super().get_form_kwargs(*args, **kwargs)
        if self.request.method == 'GET':
            kwargs.update({
                'data': self.request.GET,
            })
        return kwargs


class ReceiptDetail(DetailView):
    model = Receipt
    template_name = 'cabinet/receipt/detail.html'


class FlatServiceDetail(DetailView):
    model = Flat
    template_name = 'cabinet/tariff/index.html'


class MessageList(ListView):
    model = Message
    template_name = 'cabinet/message/index.html'

    def get_context_data(self, **kwargs):
        context = {'message_list': Message.objects.filter(owner_id=self.request.user.id)}
        return context


class MessageDetail(DetailView):
    model = Message
    template_name = 'cabinet/message/detail.html'


def delete_message(request):
    logger.info(request.POST)
    Message.objects.filter(id__in=request.POST.getlist('ids[]')).delete()
    return redirect('/cabinet/message_list')


class MasterRequestList(ListView):
    model = MasterRequest
    template_name = 'cabinet/master_request/index.html'
    ordering = ['-id']

    def get_queryset(self):
        qs = super(MasterRequestList, self).get_queryset()
        user = User.objects.get(id=self.request.user.id)
        qs = qs.filter(flat__owner=user.owner)
        return qs


class MasterRequestCreate(CreateView):
    model = MasterRequest
    template_name = 'cabinet/master_request/create.html'
    form_class = MasterRequestForm
    success_url = reverse_lazy('cabinet:master_request_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        owner = Owner.objects.get(user_id=self.request.user.id)
        context['owner'] = owner.user_id
        return context

    
def delete_master_request(request, pk):
    MasterRequest.objects.get(id=pk).delete()
    return redirect('cabinet:master_request_list')


class OwnerProfile(LoginRequiredMixin, View):

    def get(self, request):
        owner = Owner.objects.get(user_id=request.user.id)
        return render(request, 'cabinet/owner/index.html', {'owner': owner})


class UpdateOwner(UpdateView):
    model = Owner
    template_name = 'cabinet/owner/update.html'

    def get_context_data(self, **kwargs):
        owner = Owner.objects.get(user_id=self.kwargs['pk'])
        print(owner)
        context = {
            'owner_form': OwnerChangeForm(instance=owner),
            'user_form': UserChangeForm(instance=owner.user)
        }
        return context

    def post(self, request, *args, **kwargs):
        owner = Owner.objects.get(user_id=self.kwargs['pk'])
        user_form = UserChangeForm(request.POST, instance=owner.user)
        owner_form = OwnerChangeForm(request.POST, request.FILES, instance=owner)
        if user_form.is_valid() and owner_form.is_valid():
            return self.form_valid(user_form, owner_form)
        else:
            return self.form_invalid(user_form, owner_form)

    def form_valid(self, user_form, owner_form):
        created_user = user_form.save()
        created_user.username = user_form.cleaned_data['email']
        if 'password' in user_form.changed_data:
            psw = user_form.cleaned_data['password']
            created_user.set_password(user_form.cleaned_data['password'])
        created_user.save()
        owner_form.save()
        email = user_form.cleaned_data['email']
        user = authenticate(self.request, username=email, password=user_form.cleaned_data['password'])
        login(self.request, user)
        return redirect('/cabinet/owner_profile')

    def form_invalid(self, user_form, owner_form):
        """If the form is invalid, render the invalid form."""
        context = {
            'owner_form': owner_form,
            'user_form': user_form
        }
        return self.render_to_response(context)


def render_pdf_view(request, receipt_id):
    template_path = 'cabinet/receipt/pdf.html'
    requisites = PaymentDetails.objects.first()
    receipt = Receipt.objects.get(id=receipt_id)
    # print(receipt.flat.owner.user.first_name)
    print(settings.STATIC_URL)
    context = {'requisites': requisites.description,
               'static': settings.STATIC_URL,
               'receipt': receipt}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
    # create a pdf
    pisa_status = pisa.CreatePDF(
       html.encode('UTF-8'), dest=response, encoding='utf-8')
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


def print_pdf(request, receipt_id):
    template_path = 'cabinet/receipt/pdf.html'
    requisites = PaymentDetails.objects.first()
    receipt = Receipt.objects.get(id=receipt_id)
    context = {'requisites': requisites.description,
               'static': settings.STATIC_URL,
               'receipt': receipt}
    template = get_template(template_path)
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="file.pdf"'
    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
        return HttpResponse('Conversion failed!', status=404)

    return response

cabinet/templates/cabinet/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard 3</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
    <!-- IonIcons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%}">
    <link rel="stylesheet" href="{% static 'dist/css/admin.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css'%}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css'%}">
    <style>
    /* .u-under {
      display: none;
    } */
    [class*=sidebar-light-] {
        background-color: #f9fafc;;
    }
.brand-link{
  text-align: center;
  background-color: white;
}
.brand-link .brand-image{
  float: none;
}

    </style>
    {% block header%}
    {% endblock %}
</head>
<!--
`body` tag options:

  Apply one or more of the following classes to to the body tag
  to get the desired effect

  * sidebar-collapse
  * sidebar-mini
-->
<body class="hold-transition sidebar-mini">
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">перейти на сайт</a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <li class="nav-item">
                <a class="nav-link" href="#" role="button">{{ request.user.first_name }} {{ request.user.last_name }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}" role="button">выйти</a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-light-primary elevation-1">
        <!-- Brand Logo -->
        <a href="#" class="brand-link">
            <img src="{% static 'dist/img/logo.svg'%}" alt="AdminLTE Logo" class="brand-image">
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->

                    <li class="nav-item" id="summary">
                        <a href="#" class="nav-link">
                            <i class="fa fa-line-chart"></i>
                            <p>
                                Сводка
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            {% for flat in flats %}
                            <li class="nav-item" id="summary_{{ flat.id }}">
                                <a href="{% url 'cabinet:summary' flat.id %}" class="nav-link">
                                    <i class="fa fa-building"></i>
                                    <p>{{ flat.house.name }}, кв.{{ flat.number }}</p>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item" id="receipt">
                        <a href="#" class="nav-link">
                            <i class="fa fa-files-o"></i>
                            <p>
                                Квитанции
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item" id="receipt_all">
                                <a href="{% url 'cabinet:receipt_list_cabinet' %}" class="nav-link">
                                    <i class="fa fa-files-o"></i>
                                    <p>Все квитанции</p>
                                </a>
                            </li>
                            {% for flat in flats %}
                            <li class="nav-item" id="receipt_{{flat.id}}">
                                <a href="{% url 'cabinet:receipt_list_cabinet' %}?flat_id={{ flat.id }}" class="nav-link">
                                    <i class="fa fa-file-text"></i>
                                    <p>{{ flat.house.name }}, кв.{{ flat.number }}</p>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>

                    <li class="nav-item" id="tariff">
                        <a href="#" class="nav-link">
                           <i class="fa fa-money"></i>
                            <p>
                                Тарифы
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            {% for flat in flats %}
                            <li class="nav-item" id="tariff_{{flat.id}}">
                                <a href="{% url 'cabinet:detail_flatservice' flat.id %}" class="nav-link">
                                    <i class="fa fa-file-text"></i>
                                    <p>{{ flat.house.name }}, кв.{{ flat.number }}</p>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>

                    <li class="nav-item" id="message">
                        <a href="{% url 'cabinet:message_list' %}" class="nav-link">
                            <i class="fa fa-envelope"></i>
                            <p>
                                Сообщения
                            </p>
                        </a>
                    </li>
                    <li class="nav-item" id="request">
                        <a href="{% url 'cabinet:master_request_list' %}" class="nav-link">
                            <i class="fa fa-wrench"></i>
                            <p>
                                Вызов мастера
                            </p>
                        </a>
                    </li>

                    <li class="nav-item" id="owner">
                        <a href="{% url 'cabinet:owner_profile' %}" class="nav-link">
                            <i class="fa fa-user-circle"></i>
                            <p>
                                Профиль
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
    <!-- ./wrapper -->
</div>
<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<!-- Bootstrap -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<!-- AdminLTE -->
<script src="{% static 'dist/js/adminlte.js'%}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js'%}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard3.js'%}"></script>
<script src="{% static 'dist/js/custom.js'%}"></script>
<script src="{% static 'plugins/summernote/summernote-bs4.min.js'%}"></script>
<script src="{% static 'plugins/summernote/lang/summernote-ru-RU.js'%}"></script>
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js'%}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js'%}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js'%}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js'%}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js'%}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js'%}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
{% block script %}
{% endblock %}
</body>
</html>

cabinet/templates/cabinet/index.html
{% extends 'cabinet/base.html' %}

cabinet/templates/cabinet/summary.html
{% extends 'cabinet/base.html' %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>Сводка {{ flat.house.name }}, кв.{{ flat.number }}</h1>
              </div>
              <div class="col-sm-6">
              </div>
            </div>
          </div>
    </section>

    <section class="content">
    <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="small-box bg-green">
            <div class="inner">
                <h3>{{ flat.balance|floatformat:2 }} грн</h3>
                <p>Баланс по квартире</p>
            </div>
            <div class="icon">
                <i class="fa fa-money"></i>
            </div>
            <span class="small-box-footer">
                &nbsp;
            </span>
        </div>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="small-box bg-blue">
            <div class="inner">
                <h3>{{ flat.bankbook_set.first }}</h3>
                <p>Лицевой счет</p>
            </div>
            <div class="icon">
                <i class="fa fa-user"></i>
            </div>
            <span class="small-box-footer">
                &nbsp;
            </span>
        </div>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>{{ flat.avg_expenses }} грн</h3>
                <p>Средний расход за месяц</p>
            </div>
            <div class="icon">
                <i class="fa fa-pie-chart"></i>
            </div>
            <span class="small-box-footer">
                &nbsp;
            </span>
        </div>
    </div>
</div>

    <div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header with-border">
                <h3 id="pieChartTitle" class="card-title">Диаграмма расходов</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-12">
                        <p>Недостаточно данных для отображения статистики</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header with-border">
                <h3 class="card-title">Диаграмма расходов по месяцам за год</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-12">
                        <p>Недостаточно данных для отображения статистики</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</section>
{% endblock %}
{% block script %}
    <script>


        $("#summary").css('background-color', '#e1f1ea')
        $("#summary").attr('class', 'active treeview menu-open')
        $("#summary_{{ flat.id }}").attr('class', 'active')







    </script>
{% endblock %}